# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16va5-_f6j2Aq5Xp4faLhrSYSU6evTtPj
"""

import io
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import pandas as pd

def df_to_pdf(df: pd.DataFrame) -> bytes:
    """
    Convert a DataFrame to a simple PDF table and return as bytes.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    x_margin, y_margin = 40, 740
    row_height = 20

    # Header
    for idx, col in enumerate(df.columns):
        c.drawString(x_margin + idx*100, y_margin, str(col))

    # Rows
    for i, row in df.iterrows():
        y = y_margin - row_height*(i+1)
        if y < 40:
            c.showPage()
            y = y_margin
        for j, col in enumerate(df.columns):
            c.drawString(x_margin + j*100, y, str(row[col]))

    c.save()
    buffer.seek(0)
    return buffer.read()