# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16va5-_f6j2Aq5Xp4faLhrSYSU6evTtPj
"""

# utils/pdf_export.py

import tempfile
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

from utils.visuals import (
    plot_overall_heatmap, plot_risk_distribution
)

def generate_pdf_report(df):
    """
    Creates 'performance_report.pdf' in the working directory
    containing overall heatmap and risk distribution.
    """
    # Create temporary images
    fig1 = plot_overall_heatmap(df)
    tmp1 = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
    fig1.savefig(tmp1.name, bbox_inches="tight")
    fig2 = plot_risk_distribution(df)
    tmp2 = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
    fig2.write_image(tmp2.name)

    # Build PDF
    c = canvas.Canvas("performance_report.pdf", pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width/2, height-50, "Student Performance Report")

    # Heatmap
    c.drawImage(ImageReader(tmp1.name), 40, height-380, width=520, height=300)
    c.showPage()

    # Risk distribution
    c.setFont("Helvetica-Bold", 14)
    c.drawCentredString(width/2, height-50, "Risk Distribution")
    c.drawImage(ImageReader(tmp2.name), 40, height-380, width=520, height=300)
    c.save()

    return "performance_report.pdf"